openapi: 3.0.0
info:
    title: BlinksMedia
    version: 1.0.0
servers:
    - {url: /}
components:
    securitySchemes: {bearerAuth: {type: http, scheme: bearer}}
tags:
    - {name: application}
    - {name: 'application > user'}
    - {name: 'application > user > auth'}
    - {name: 'application > videos'}
    - {name: 'application > image-upload'}
paths:
    /application/users/auth/login: {post: {tags: ['application > user > auth'], summary: user-login, requestBody: {content: {application/json: {schema: {type: object, example: {email: demouser@blinksmedia.in, password: Demo@1234}}}}}, responses: {'200': {description: 'Successful response', content: {application/json: {}}}}}}
    /application/videos-upload: {post: {tags: ['application > videos'], summary: upload-video-file, requestBody: {content: {multipart/form-data: {schema: {type: object, properties: {video: {type: string, format: binary}}}}}}, responses: {'200': {description: 'Successful response', content: {application/json: {}}}}}}
    /application/videos: {post: {tags: ['application > videos'], summary: create-video-metadata, requestBody: {content: {application/json: {schema: {type: object, example: {title: 'Video test 5', status: live, thumbnail_url: 'https://res.cloudinary.com/ditzlnzmw/image/upload/v1727453319/thumbnails/pvcnxxmdnyje2gfemzzq.webp', thumbnail_public_id: thumbnails/pvcnxxmdnyje2gfemzzq, video_url: 'https://res.cloudinary.com/ditzlnzmw/video/upload/v1727404430/original-videos/itiny-url-shortener-demo.mp4', video_public_id: original-videos/itiny-url-shortener-demo}}}}}, security: [{bearerAuth: []}], responses: {'200': {description: 'Successful response', content: {application/json: {}}}}}}
    /application/images-upload: {post: {tags: ['application > image-upload'], summary: upload-video-thumbnail, requestBody: {content: {multipart/form-data: {schema: {type: object, properties: {thumbnail: {type: string, format: binary}}}}}}, responses: {'200': {description: 'Successful response', content: {application/json: {}}}}}}
